In [36]:
def table(n = 10):
    f= open("table.csv","w+")
    f.write("i,j,k\n")
    for i in range(n + 1):
        for j in range(11):
            row = str(i) +"," + str(j) + "," + str(i * j)
            f.write(row  + "\n")
            
    f.close()

In [37]:
table(1000)

# Analyze table

In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [39]:
data_frame = pd.read_csv('table.csv')

In [40]:
data_frame

          i   j      k
0         0   0      0
1         0   1      0
2         0   2      0
3         0   3      0
4         0   4      0
5         0   5      0
6         0   6      0
7         0   7      0
8         0   8      0
9         0   9      0
10        0  10      0
11        1   0      0
12        1   1      1
13        1   2      2
14        1   3      3
15        1   4      4
16        1   5      5
17        1   6      6
18        1   7      7
19        1   8      8
20        1   9      9
21        1  10     10
22        2   0      0
23        2   1      2
24        2   2      4
25        2   3      6
26        2   4      8
27        2   5     10
28        2   6     12
29        2   7     14
...     ...  ..    ...
10981   998   3   2994
10982   998   4   3992
10983   998   5   4990
10984   998   6   5988
10985   998   7   6986
10986   998   8   7984
10987   998   9   8982
10988   998  10   9980
10989   999   0      0
10990   999   1    999
10991   999   2   1998
10992   999   3   2997
10993   999   4   3996
10994   999   5   4995
10995   999   6   5994
10996   999   7   6993
10997   999   8   7992
10998   999   9   8991
10999   999  10   9990
11000  1000   0      0
11001  1000   1   1000
11002  1000   2   2000
11003  1000   3   3000
11004  1000   4   4000
11005  1000   5   5000
11006  1000   6   6000
11007  1000   7   7000
11008  1000   8   8000
11009  1000   9   9000
11010  1000  10  10000

[11011 rows x 3 columns]

In [42]:
from sklearn.cross_validation import train_test_split

featured_column_name = ['i', 'j']
predict_column_name = ['k']

X = data_frame[featured_column_name].values
y = data_frame[predict_column_name].values

split_test_size = 0.3
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = split_test_size, random_state = 42)

In [43]:
print("{0:0.2f}% in training set".format((len(X_train)/len(data_frame.index)) * 100))
print("{0:0.2f}% in test set".format((len(X_test)/len(data_frame.index)) * 100))

69.99% in training set
30.01% in test set

In [72]:
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(X_train, y_train.ravel())
prediction_nb = nb_model.predict(X_test)

In [59]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, prediction_nb)

print (accuracy)

0.0874697336562


# Regression

In [74]:
#doesn't work now
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train.ravel())
prediction_lr = lr_model.predict(X_test)
print (prediction_lr.size , " ",  y_test.size)
accuracy = metrics.accuracy_score(y_test, prediction_lr)
print(accuracy)

3304   3304

ValueError: Can't handle mix of multiclass and continuous

In [68]:
prediction_lr

array([ 1148.65528173,  5280.12683632,  6859.38886606, ...,  4094.13636363,
        2549.80708961,  1493.96198839])

In [69]:
y_test

array([[ 189],
       [5736],
       [8680],
       ...,
       [3735],
       [2550],
       [   0]])